// Bonds (DESIGN 9.2, docs/STORY.md): heart scenes, daily wishes and arrival lines. core/bonds.mjs (play package) reads
// them; the bonds panels (ui package) show them in the chapter-card layout.
//
// HEART_SCENES[personId][3 | 6 | 9] = { lines: [{ who, text } × 3], reward: { decor: kind } | { coins: n } }
//   Every resident family member, and every villager or neighbour who earns hearts (Ada, Cora, Mai, Gus), has all three. `who` is a person id from people.mjs. The player never speaks.
// WISHES[personId] = [{ text, need: { kind, near: 'home' } }]
//   A small, visible wish: a decoration of that kind placed near the person's cottage grants it.
// ARRIVALS[familyId] = [{ who, text } × 3]: what the family says on the day they move in.

const scene = (reward, ...lines) => ({ lines: lines.map(([who, text]) => ({ who, text })), reward });
// The default is the before-building scene. Only its dialogue changes after the place opens; the gift stays the same.
const afterBuilding = (kind, before, ...lines) => ({ ...before,
  variants: [{ when: { type: 'count', key: kind, value: 1 }, lines: lines.map(([who, text]) => ({ who, text })) }],
});

export const HEART_SCENES = {
  // ── The Tran family ──
  minh: {
    3: scene({ decor: 'bench' },
      ['minh', 'I fixed the creaky step on your porch. Do not thank me. It kept me awake.'],
      ['ada', 'Ellis built that step. He said it creaked to warn him of visitors.'],
      ['minh', 'Then I made you a bench that keeps quiet. For Ada\'s visitors.']),
    6: scene({ decor: 'hay_bale' },
      ['lan', 'Minh has been in the old mill again. He comes home covered in sawdust and secrets.'],
      ['minh', 'The mill wheel is sound. Good oak. It could turn again, if the brook ran full.'],
      ['minh', 'It used to run full. I would like to know what changed upriver.']),
    9: scene({ decor: 'lamp' },
      ['bo', 'Dad made me a desk for school, with my name on it! B-O. Two letters, and it took him all night.'],
      ['minh', 'A good desk lasts forty years. I want Bo\'s children to sit at it.'],
      ['minh', 'You gave us a street to grow old on. Here is a lamp for your path, so you always find the way home.']),
  },
  lan: {
    3: scene({ decor: 'flowers' },
      ['lan', 'I baked with your flour today, and the whole street came to the door!'],
      ['lan', 'My mother sold bread by a river like this one. I thought I had forgotten how it felt.'],
      ['lan', 'Take these flowers. A kitchen window needs something to look at.']),
    6: scene({ decor: 'flowerpot' },
      ['lan', 'Ada lent me her recipe book. Half of it is notes from Ellis: "more butter", "more butter".'],
      ['ada', 'He was right every time. Do not tell him.'],
      ['lan', 'I am writing my own pages in it now. One day it can be Pip\'s.']),
    9: scene({ decor: 'tree' },
      ['lan', 'We had a supper on the street last night. Every family brought a dish. Even Gus came.'],
      ['gus', 'I came for the food. Only the food.'],
      ['lan', 'Hollowbrook is home now. A blossom tree for your farm, so you remember the first spring.']),
  },
  bo: {
    3: scene({ decor: 'flowers' },
      ['bo', 'I found a frog by the brook! His name is Captain. He is very brave.'],
      ['pip', 'Can Captain come to school too?'],
      ['bo', 'Only if he sits still. I can\'t either. Here, I picked these for you!']),
    6: scene({ decor: 'scarecrow' },
      ['bo', 'I can read the sign on the old mill now! It says HOLLOWBROOK MILL, 1904.'],
      ['bo', 'There is a big chain on the door. Why would anybody lock up a mill?'],
      ['pip', 'Maybe there is treasure inside!']),
    9: scene({ decor: 'bush' },
      ['bo', 'I wrote a story and Mum gave it a gold star! It is about our house. And Captain.'],
      ['lan', 'He read it to the whole street. Twice.'],
      ['bo', 'You were in it too. You were the hero! I planted this bush for you myself.']),
  },
  // ── The Okafor family ──
  grace: {
    3: scene({ decor: 'bench' },
      ['grace', 'Your hens are in fine shape. Clean coop, good feed. I am impressed.'],
      ['grace', 'In the city I treated poodles in raincoats. This is much better.'],
      ['grace', 'A bench for the coop yard. Hens like company while they lay.']),
    6: scene({ decor: 'flowerpot' },
      ['grace', 'Mai\'s goose had a sore foot, so I walked over to Lotus Farm.'],
      ['mai', 'And she wouldn\'t take a coin! Tell her she is the best.'],
      ['grace', 'A village with a vet is a village where animals can live. Thank you for having us.']),
    9: scene({ decor: 'lamp' },
      ['zara', 'Mum stayed up all night with a calf at Old Mill Farm.'],
      ['gus', 'She saved it. The calf, I mean. Your mother is... very good, child.'],
      ['grace', 'Gus said thank you. Out loud. I think that is a first for Hollowbrook.']),
  },
  sam: {
    3: scene({ decor: 'street_lamp' },
      ['sam', 'I deliver letters to every house in Hollowbrook. It takes me four minutes.'],
      ['sam', 'Then I take the long way home, past the brook. Best part of the job.'],
      ['sam', 'You have mail, by the way. Ha! I always wanted to say that.']),
    6: scene({ decor: 'bench' },
      ['sam', 'There is a letter in the old sorting box at the post office. Never delivered. It is addressed to Gus.'],
      ['sam', 'The postmark is from the night of the last festival. The night the stage burned.'],
      ['sam', 'Should I give it to him? Let me think about it.']),
    9: scene({ decor: 'bench' },
      ['sam', 'I gave Gus the letter. He read it on the bridge and said nothing for an hour.'],
      ['gus', 'Took the long way, did it, postman? ...Thank you.'],
      ['sam', 'Some letters take the long way. Here is a bench by the mailbox, for reading slowly.']),
  },
  zara: {
    3: afterBuilding("school", scene({ decor: 'flowers' },
      ['zara', 'I have read every book in our house. Twice. I need a library.'],
      ['grace', 'Or a school with a library. One day soon, I think.'],
      ['zara', 'I made you a bookmark. It is a carrot, because carrots are good for your eyes!']),
      ["zara", "I have read every book in our house. Twice. What should I read next?"],
      ["grace", "The school shelves have room for more books. We can choose some together."],
      ["zara", "I made you a bookmark. It is a carrot, because carrots are good for your eyes!"]),
    6: scene({ decor: 'flowers' },
      ['zara', 'Bo says the old mill is haunted. That is not even scientific.'],
      ['zara', 'I looked through the window. There are flour sacks still stacked up, like everyone left in one night.'],
      ['zara', 'Ghosts don\'t leave flour. People do.']),
    9: scene({ decor: 'tree' },
      ['zara', 'I am writing a book about Hollowbrook. Chapter one is about you.'],
      ['grace', 'She has eleven chapters so far. You are in all of them.'],
      ['zara', 'This tree is for the farm. When it is big, I will read under it.']),
  },
  // ── The Lindqvist family ──
  elin: {
    3: scene({ decor: 'flowers' },
      ['elin', 'I set up my easel on the hill. Your fields make the best stripes.'],
      ['elin', 'Green, gold, green. If you plant pumpkins, I will need more orange paint.'],
      ['elin', 'Flowers for your door. Every painting needs a little red.']),
    6: scene({ decor: 'lamp' },
      ['elin', 'I found an old poster in the attic: "Hollowbrook Harvest Festival". Look at all those lanterns!'],
      ['olaf', 'I remember it. The whole valley came. Then one year it just... stopped.'],
      ['elin', 'I am going to paint it the way it was. Then maybe we can make it real again.']),
    9: scene({ decor: 'lamp' },
      ['elin', 'My painting of your farm sold in the city. People asked where Hollowbrook is.'],
      ['olaf', 'She told them: "Follow the brook until it feels like home."'],
      ['elin', 'A lamp for your path. Your farm at dusk is my favourite colour.']),
  },
  olaf: {
    3: scene({ decor: 'bench' },
      ['olaf', 'Forty years at sea, and I never saw water as clear as your brook.'],
      ['olaf', 'Mind you, it was wider once. As a boy I paddled down it all the way to the mill.'],
      ['olaf', 'Here, a bench. A sailor needs somewhere to sit and watch the water.']),
    6: scene({ decor: 'picket' },
      ['olaf', 'I walked upriver yesterday and met a fellow fishing. Grey beard, terrible hat.'],
      ['olaf', 'Said his name was Ellis, and to tell you the fish are biting and he is "looking into something".'],
      ['ada', 'Looking into something. Fifty years, and that man still talks in riddles.']),
    9: scene({ coins: 120 },
      ['olaf', 'I have decided. I am staying in Hollowbrook for good.'],
      ['elin', 'He unpacked his ship in a bottle. That is how I knew before he did.'],
      ['olaf', 'Take this from my sea chest. Old sailor\'s silver, for new beginnings.']),
  },
  // ── The Reyes family ──
  marisol: {
    3: afterBuilding("clinic", scene({ decor: 'flowerpot' },
      ['marisol', 'I bandaged Tomas\'s thumb again. Third time this week.'],
      ['tomas', 'The engine started, though!'],
      ['marisol', 'Hollowbrook needs a proper clinic, not just me with a first-aid box. I am starting a list.']),
      ["marisol", "I bandaged Tomas's thumb again. Third time this week."],
      ["tomas", "The engine started, though!"],
      ["marisol", "A proper treatment room, clean shelves, and Dr Hazel next door. This clinic was worth every name on my list."]),
    6: afterBuilding("clinic", scene({ decor: 'flowers' },
      ['marisol', 'Every family has signed my list. Everyone wants the clinic back.'],
      ['marisol', 'I wrote to Dr Hazel, my old teacher from nursing school. She retired to the coast.'],
      ['marisol', 'She wrote back: "Save me a sunny room and a place in the garden." I have added both to the list.']),
      ["marisol", "All those names on my list, and now a clinic full of neighbours. We did it."],
      ["marisol", "Dr Hazel brought her old medical books. I am learning from her all over again."],
      ["marisol", "There is room for a vase on every windowsill. That is my next list."]),
    9: afterBuilding("clinic", scene({ decor: 'bench' },
      ['marisol', 'Dr Hazel is coming to visit! She wants to see the old clinic.'],
      ['pia', 'I am going to show her my plasters. I have forty-two.'],
      ['marisol', 'You made this possible. A bench for the clinic garden, for whoever waits there.']),
      ["marisol", "Dr Hazel asked me to choose flowers for the clinic garden. It is a much nicer kind of list."],
      ["pia", "I am going to count them. The flowers, not the doctors."],
      ["marisol", "You made this possible. A bench for the clinic garden, for whoever waits there."]),
  },
  tomas: {
    3: scene({ coins: 50 },
      ['tomas', 'Your wheelbarrow squeaked, so I oiled it. Now it sings.'],
      ['tomas', 'In the city I fixed cars all day. Here I fix everything.'],
      ['tomas', 'I found these coins under your old tractor seat. Finders keepers, but they are yours.']),
    6: scene({ decor: 'scarecrow' },
      ['tomas', 'I looked at the old mill gears. Good steel. Rusty, but good.'],
      ['tomas', 'Funny thing, though. The sluice gate upriver is shut tight, with a new padlock.'],
      ['tomas', 'Who locks a river? I will ask Sam who owns that land.']),
    9: afterBuilding("school", scene({ decor: 'lamp' },
      ['pia', 'Papa made a clock for our kitchen! It rings all by itself at nine o\'clock.'],
      ['tomas', 'Not by itself. With a bicycle bell and rather a lot of patience.'],
      ['tomas', 'You gave a mechanic a place to be useful. Here, a lamp I rewired. It never flickers.']),
      ["pia", "Papa fixed the school bell! Now it rings all by itself at nine o'clock."],
      ["tomas", "Not by itself. With a clock I built from a bicycle."],
      ["tomas", "You gave a mechanic a place to be useful. Here, a lamp I rewired. It never flickers."]),
  },
  pia: {
    3: scene({ decor: 'flowers' },
      ['pia', 'I counted all your hens! There are... a lot.'],
      ['pia', 'I counted the flowers too. I got to sixty-three, and then a bee came.'],
      ['pia', 'This flower is for you. It is number sixty-four.']),
    6: scene({ decor: 'flowers' },
      ['pia', 'Pip and I made a club. It is called the Brook Club. You can be in it.'],
      ['pip', 'The password is "frog". Do not tell anyone.'],
      ['pia', 'We found an old key in the brook! It is all rusty. Pip says it opens a pirate ship.']),
    9: scene({ decor: 'tree' },
      ['pia', 'I can count to a thousand now! Do you want to hear?'],
      ['marisol', 'Please say no. We will be here until dinner.'],
      ['pia', 'Okay. Then here is a tree. It is one tree. That is easy to count.']),
  },
  // ── Villagers and neighbours who post orders (they earn hearts too) ──
  // Ada's scenes carry the Ellis thread; Gus's carry the lost Harvest Festival.
  ada: {
    3: scene({ decor: 'flowerpot' },
      ['ada', 'I found Ellis\'s old hat in the shed. It still smells of pipe smoke and brook water.'],
      ['pip', 'Can I wear it? I will be careful. Mostly.'],
      ['ada', 'It fits you better than it ever fitted him. Here, a flowerpot for the porch. He made it.']),
    6: scene({ decor: 'bench' },
      ['ada', 'Ellis wrote. He says the fish are thin and the brook runs low. He does not say when he is coming home.'],
      ['june', 'He will come, Ada. He always does.'],
      ['ada', 'I know, dear. I set his place at the table anyway. Sit with me a while.']),
    9: scene({ decor: 'street_lamp' },
      ['ada', 'When you came, the house was dark and the weeds were up to the windows.'],
      ['ada', 'Now look. Lights on Brook Lane, bread in the oven, children on the hill.'],
      ['ada', 'Ellis kept a lamp for the day Hollowbrook came home. I think that day is today.']),
  },
  cora: {
    3: scene({ decor: 'flowers' },
      ['cora', 'Bo asked me today why the sky is blue. Then why the brook is brown. Then why Gus is grumpy.'],
      ['bo', 'She did not know the last one!'],
      ['cora', 'Nobody does, Bo. Some flowers for your gate, from the class garden.']),
    6: scene({ decor: 'bench' },
      ['cora', 'I found the old school register in a cupboard. Ada is in it. So is Ellis, and so is Gus.'],
      ['cora', 'Gus was marked late every single day. Every one.'],
      ['cora', 'I have framed the page. A bench for your farm, so the late ones have somewhere to rest.']),
    9: scene({ decor: 'fountain' },
      ['cora', 'The class wrote a play about Hollowbrook. Pip is the brook. Zara is the mill. Bo is a very loud hen.'],
      ['zara', 'I wrote most of it. Bo wrote the clucking.'],
      ['cora', 'You are in it too, as the farmer who brought the village home. A fountain, from all of us.']),
  },
  mai: {
    3: scene({ decor: 'hay_bale' },
      ['mai', 'My ducks have walked all the way to your brook again. I think they like your farm better.'],
      ['mai', 'Traitors, all of them. Well, I cannot blame them.'],
      ['mai', 'Here is a hay bale from Lotus Farm. The hens can argue over it.']),
    6: scene({ decor: 'bush' },
      ['mai', 'My grandmother and Ada traded eggs for jam across that fence. Every Sunday for thirty years.'],
      ['ada', 'Her plum jam was terrible. I never told her.'],
      ['mai', 'She knew! She said your eggs were small. A bush from my garden, to keep the Sundays going.']),
    9: scene({ decor: 'scarecrow' },
      ['mai', 'I am entering my ducks in the Harvest Festival, if it ever comes back. They will need a rival.'],
      ['pip', 'We will enter Cloud and Drizzle! They can do tricks. One trick.'],
      ['mai', 'Then it is war. A friendly war. Take this scarecrow. It only scares my ducks a little.']),
  },
  gus: {
    3: scene({ decor: 'picket' },
      ['gus', 'Hmph. Brought you some fence posts. Yours lean.'],
      ['gus', 'Do not look at me like that. I had spare ones. That is all.'],
      ['ada', 'Gus, carrying fence posts for a neighbour. Ellis will never believe it.']),
    6: scene({ decor: 'bench' },
      ['gus', 'Found an old poster in my barn. The last Harvest Festival. I won the bread prize that year.'],
      ['gus', 'Ada came second. She has never forgiven me.'],
      ['ada', 'He used my oven, dear. My oven. Sit down, Gus, before you fall over from pride.']),
    9: scene({ decor: 'tree' },
      ['gus', 'The festival stopped the year the mill closed. Somebody should start it again.'],
      ['gus', 'Not me. I am too old. You, maybe. With Ada. I would bring bread.'],
      ['ada', 'Did you hear that? Gus wants a festival. Write it down before he takes it back.']),
  },
};

const wish = (kind, text) => ({ text, need: { kind, near: 'home' } });
export const WISHES = {
  minh: [wish('bench', 'A bench by our door, so I can sit and admire my own woodwork.'), wish('tree', 'A tree by the cottage, for some shade over my workbench.')],
  lan: [wish('flowers', 'Flowers under the kitchen window, please. Cooking is nicer with a view.'), wish('lamp', 'A lamp by the door, for late suppers on the step.')],
  bo: [wish('bush', 'A bush by our house for hide-and-seek! Pip always finds me.'), wish('flowers', 'Flowers by the door for Mum. It is a surprise!')],
  grace: [wish('bush', 'A bush by the cottage. The sparrows need somewhere to gossip.'), wish('bench', 'A bench by our door, for the end of a long day.')],
  sam: [wish('lamp', 'A lamp by our door. I come home late from the long way round.'), wish('bench', 'A bench by the house, for reading the postcards I am not supposed to read.')],
  zara: [wish('tree', 'A tree by our house to read under. A big one, please.'), wish('flowers', 'Flowers by the door. I want to learn all their names.')],
  elin: [wish('flowers', 'Red flowers by the cottage. My painting needs a little red.'), wish('tree', 'A blossom tree by the door. I will paint it in every season.')],
  olaf: [wish('bench', 'A bench by the door, facing the brook if you can.'), wish('lamp', 'A lamp by the cottage. A sailor likes a light in harbour.')],
  marisol: [wish('flowers', 'Flowers by the door. They do more good than half my medicines.'), wish('bench', 'A bench by the house, where neighbours can sit and talk.')],
  tomas: [wish('lamp', 'A lamp by the workshop door. I fix things late.'), wish('bush', 'A bush by the cottage, to hide my spare parts behind.')],
  pia: [wish('flowers', 'Flowers by our house! Lots! So I can count them.'), wish('bush', 'A bush by the door. A round one, like a sheep.')],
};

const say = (...lines) => lines.map(([who, text]) => ({ who, text }));
export const ARRIVALS = {
  tran: say(['minh', 'The cottage is perfect. Well, the door sticks. I will fix it tonight.'],
    ['lan', 'I can smell bread from your farm! We are going to be very good neighbours.'],
    ['bo', 'Is that the school? With the bell? Can I ring it?']),
  okafor: say(['sam', 'Special delivery: one Okafor family, a little travel-worn.'],
    ['grace', 'I hear you keep hens. I will come and say hello to them tomorrow.'],
    ['zara', 'Bo says the school is opening. I already packed my pencil case.']),
  lindqvist: say(['elin', 'Look at the light on the brook! I am unpacking my paints first.'],
    ['olaf', 'And I am unpacking my chair. Every porch needs an old sailor.'],
    ['elin', 'We came for one summer. We might stay for all of them.']),
  reyes: say(['tomas', 'Anything here need fixing? Never mind, I will find it.'],
    ['marisol', 'No clinic yet, I see. We will work on that.'],
    ['pia', 'I counted the cottages! Four! Is that a lot? It feels like a lot.']),
};
